import Head from 'next/head'

export default function Home() {
  return (
    <div className='pb-20'>
      <Head>
        <title>Hunting_Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='text-center mt-24 space-y-4 '>
        <h1 className='text-6xl font-bold text-blue-800'>Hunting_Coder</h1>
        <p className='text-xl'>A Hunting_Coder by a Hunting_Coder</p>
      </div>      

      <div className='text-center pt-10 space-y-5 text-lg'>
        <div>
          <h1 className='text-2xl'>How to learn Javascript</h1>
          <p className='text-base'>learn Javascript in one video is the best way to learn Javascript</p>
        </div>
      </div>
    </div>
  )
}