import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hunting_Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  
      <nav>
          
      </nav>
      
    </div>
  )
}
